package com.mono9rome.typst_note_app.ui.component

import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectHorizontalDragGestures
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.width
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.pointer.PointerIcon
import androidx.compose.ui.input.pointer.pointerHoverIcon
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.unit.dp
import com.mono9rome.typst_note_app.ui.borderColor

// This component is generated by Gemini 3 Pro.

// リサイザーにホバーしたときのカーソルアイコン
// ※ プラットフォームごとに実装を分ける
expect val horizontalResizeIcon: PointerIcon

/**
 * リサイズ用のドラッグハンドルコンポーネント
 */
@Composable
fun ResizeHandle(
    onDragStart: () -> Unit,
    onDrag: (Float) -> Unit
) {
    Box(
        modifier = Modifier
            .width(6.dp)
            .fillMaxHeight()
            .background(borderColor)
            .pointerHoverIcon(horizontalResizeIcon)
            .pointerInput(Unit) {
                detectHorizontalDragGestures(
                    onDragStart = { onDragStart() } // ドラッグ開始を通知
                ) { change, dragAmount ->
                    change.consume()
                    onDrag(dragAmount)
                }
            }
    )
}