package com.mono9rome.typst_note_app.ui.container

import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectHorizontalDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Menu
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.PointerIcon
import androidx.compose.ui.input.pointer.pointerHoverIcon
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.mono9rome.typst_note_app.ui.preview.PreviewConfig

// Remark : The UI logic is generated by Gemini 3 Pro.

// リサイザーにホバーしたときのカーソルアイコン
// ※ プラットフォームごとに実装を分ける
expect val horizontalResizeIcon: PointerIcon

@Composable
fun MainScreenContainer(
    modifier: Modifier = Modifier,
    sidebarContent: @Composable BoxScope.(Modifier) -> Unit,
    editorContent: @Composable BoxScope.(Modifier) -> Unit,
    viewerContent: @Composable BoxScope.(Modifier) -> Unit,
) {
    var isSidebarOpen by remember { mutableStateOf(false) }

    // UI に反映する「実際の」状態（coerceIn で制限される）
    var sidebarWidth by remember { mutableStateOf(200.dp) }
    var editorPreviewRatio by remember { mutableFloatStateOf(0.5f) }

    // ドラッグ中の「仮想の（制限のない）」状態を保持する変数
    var unconstrainedSidebarWidth by remember { mutableStateOf(200.dp) }
    var unconstrainedRatio by remember { mutableFloatStateOf(0.5f) }

    val density = LocalDensity.current


    Row(modifier.fillMaxSize()) {

        // 一番左の細いメニューバー（常に表示）
        Column(
            modifier = Modifier
                .width(40.dp)
                .fillMaxHeight()
                .background(Color.LightGray), // わかりやすく色をつけています
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // 開閉用のトグルボタン
            IconButton(
                onClick = { isSidebarOpen = !isSidebarOpen },
                modifier = Modifier
                    .size(32.dp)
                    .padding(top = 12.dp)
            ) {
                Icon(
                    imageVector = Icons.Default.Menu,
                    contentDescription = "サイドバー切替",
                    modifier = Modifier.size(18.dp)
                )
            }
        }

        // --- サイドバー領域 ---
        if (isSidebarOpen) {
            Row {
                Box(
                    modifier = Modifier
                        .width(sidebarWidth)
                        .fillMaxHeight()
                        .background(Color(0xFFEEEEEE))
                ) {
                    sidebarContent(Modifier.padding(8.dp))
                }

                ResizeHandle(
                    // ドラッグ開始時に、現在の実際の幅を仮想幅としてスナップショット
                    onDragStart = { unconstrainedSidebarWidth = sidebarWidth },
                    onDrag = { dragAmountPx ->
                        val dragAmountDp = with(density) { dragAmountPx.toDp() }
                        // 仮想幅にドラッグ量を足す（マイナス方向にも無限にいく）
                        unconstrainedSidebarWidth += dragAmountDp
                        // UI に反映する幅は、仮想幅を制限したものにする
                        sidebarWidth = unconstrainedSidebarWidth.coerceIn(150.dp, 400.dp)
                    }
                )
            }
        }

        // --- エディタ ＆ プレビュー領域 ---
        // BoxWithConstraints でこの領域のピクセル幅を取得する
        BoxWithConstraints(modifier = Modifier.weight(1f).fillMaxHeight()) {
            val totalWidthPx = constraints.maxWidth

            Row(Modifier.fillMaxSize()) {
                Box(
                    modifier = Modifier
                        .weight(editorPreviewRatio)
                        .fillMaxHeight()
                        .background(Color.White)
                ) {
                    editorContent(Modifier.padding(8.dp))
                }

                ResizeHandle(
                    // ドラッグ開始時に、現在の比率を仮想比率としてスナップショット
                    onDragStart = { unconstrainedRatio = editorPreviewRatio },
                    onDrag = { dragAmountPx ->
                        val ratioChange = dragAmountPx / totalWidthPx.toFloat()
                        // 仮想比率にドラッグ量を足す
                        unconstrainedRatio += ratioChange
                        // UI に反映する比率は制限をかける
                        editorPreviewRatio = unconstrainedRatio.coerceIn(0.1f, 0.9f)
                    }
                )

                Box(
                    modifier = Modifier
                        .weight(1f - editorPreviewRatio)
                        .fillMaxHeight()
                        .background(Color.White)
                ) {
                    viewerContent(Modifier.padding(8.dp))
                }
            }
        }
    }
}

/**
 * リサイズ用のドラッグハンドルコンポーネント
 */
@Composable
fun ResizeHandle(
    onDragStart: () -> Unit,
    onDrag: (Float) -> Unit
) {
    Box(
        modifier = Modifier
            .width(6.dp)
            .fillMaxHeight()
            .background(Color.Black)
            .pointerHoverIcon(horizontalResizeIcon)
            .pointerInput(Unit) {
                detectHorizontalDragGestures(
                    onDragStart = { onDragStart() } // ドラッグ開始を通知
                ) { change, dragAmount ->
                    change.consume()
                    onDrag(dragAmount)
                }
            }
    )
}

@Preview(
    widthDp = PreviewConfig.WIDTH_DP_HD,
    heightDp = PreviewConfig.HEIGHT_DP_HD,
    showBackground = true
)
@Composable
fun MainScreenPreview() {
    MainScreenContainer(
        sidebarContent = { modifier -> Text("sidebar", modifier) },
        editorContent = { modifier -> Text("editor", modifier) },
        viewerContent = { modifier -> Text("viewer", modifier) },
    )
}