package com.mono9rome.typst_note_app.ui.editor

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.gestures.scrollBy
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.BasicTextField
import androidx.compose.foundation.verticalScroll
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.PointerEventPass
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.layout.onSizeChanged
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.TextLayoutResult
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.drawText
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.input.TextFieldValue
import androidx.compose.ui.text.rememberTextMeasurer
import androidx.compose.ui.text.style.LineHeightStyle
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.mono9rome.typst_note_app.ui.SourceCode
import kotlinx.coroutines.delay
import kotlinx.coroutines.isActive

// カレント行のハイライト色
private val activeLineColor = Color(0x330000FF) // 透明度を持たせた青

// The UI logic is mostly generated by Gemini 3 Pro.

@Composable
fun CodeEditorUI(
    sourceText: String,
    fontSizeSp: Float,
    onEdited: (SourceCode) -> Unit,
) {
    // TextFieldValue を使用することでカーソル位置を保持できる
    var textFieldValue by remember {
        mutableStateOf(TextFieldValue(""))
    }
    // テキストのレイアウト結果（高さや各行の座標情報）を保持する
    var textLayoutResult by remember { mutableStateOf<TextLayoutResult?>(null) }

    // 縦と横、それぞれのスクロール状態を保持する
    val verticalScrollState = rememberScrollState()
    val horizontalScrollState = rememberScrollState()

    val density = LocalDensity.current

    // エディタの「目に見えている領域」の高さを保持する状態
    var viewportHeight by remember { mutableIntStateOf(0) }

    // ドラッグ中のポインタのY座標を保持する（ドラッグしていない時は NaN）
    var pointerY by remember { mutableFloatStateOf(Float.NaN) }

    // 行番号を描画するための測量ツール
    val textMeasurer = rememberTextMeasurer()

    // text style
    val editorTextStyle = TextStyle(
        fontFamily = FontFamily.Monospace,
        fontSize = fontSizeSp.sp,
        lineHeight = (fontSizeSp * 1.8f).sp,
        lineHeightStyle = LineHeightStyle(
            alignment = LineHeightStyle.Alignment.Center,
            trim = LineHeightStyle.Trim.None
        )
    )

    // カーソル位置（selection）が変更されるたびに発火する監視ロジック
    LaunchedEffect(textFieldValue.selection) {
        val layoutResult = textLayoutResult ?: return@LaunchedEffect

        // 現在のカーソル位置のオフセットを取得
        val cursorOffset = textFieldValue.selection.start.coerceIn(0, textFieldValue.text.length)

        // カーソルの矩形情報（Top, Bottom, Left, Rightのピクセル座標）を取得
        val cursorRect = layoutResult.getCursorRect(cursorOffset)

        val cursorTop = cursorRect.top.toInt()
        val cursorBottom = cursorRect.bottom.toInt()

        val currentScroll = verticalScrollState.value

        // 余白（画面のギリギリではなく、少し手前でスクロールさせるためのバッファ）
        val paddingEnd = 50

        // [下に隠れた場合] カーソルの下端が、現在のスクロール位置 ＋ 画面の高さ を超えたら
        if (cursorBottom > currentScroll + viewportHeight) {
            verticalScrollState.animateScrollTo(cursorBottom - viewportHeight + paddingEnd)
        }
        // [上に隠れた場合] カーソルの上端が、現在のスクロール位置 より上になったら
        else if (cursorTop < currentScroll) {
            verticalScrollState.animateScrollTo(cursorTop - paddingEnd)
        }

        // ※横スクロール（horizontalScrollState）についても、
        // cursorRect.left と cursorRect.right を使って全く同じロジックで自動追従を作れます。
    }
    // エッジスクロールのループ処理
    LaunchedEffect(pointerY) {
        // ドラッグ中でなければ何もしない
        if (pointerY.isNaN()) return@LaunchedEffect

        val edgeZone = 80f      // スクロールが発動する端からの距離（ピクセル）
        val scrollSpeed = 15f   // 1フレームあたりのスクロール量（大きくすると高速に）

        // ポインタが有効な間、ループを回し続ける
        while (isActive && !pointerY.isNaN()) {
            if (pointerY < edgeZone) {
                // 上端にいる場合：上へスクロール（マイナス方向）
                verticalScrollState.scrollBy(-scrollSpeed)
            } else if (pointerY > viewportHeight - edgeZone) {
                // 下端にいる場合：下へスクロール（プラス方向）
                verticalScrollState.scrollBy(scrollSpeed)
            } else {
                // 端にいない場合はループを抜けて待機
                break
            }
            // 約60FPS間隔（16ミリ秒）でスムーズに連続スクロールさせる
            delay(16)
        }
    }
    Box(
        modifier = Modifier
            .fillMaxSize()
            // Row のサイズを測るための onSizeChanged
            .onSizeChanged { size ->
                // スクロール可能な表示領域の高さを取得
                viewportHeight = size.height
            }
            // PointerEventPass.Initial を使うことで、TextField の標準の選択機能を邪魔せずに
            // 座標だけを「盗み見」することができます。
            .pointerInput(Unit) {
                awaitPointerEventScope {
                    while (true) {
                        val event = awaitPointerEvent(PointerEventPass.Initial)
                        val change = event.changes.firstOrNull()

                        // ポインタが押されている（ドラッグ中）場合のみY座標を更新
                        if (change != null && change.pressed) {
                            pointerY = change.position.y
                        } else {
                            pointerY = Float.NaN
                        }
                    }
                }
            }
    ) {
        Row(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(verticalScrollState)
                .padding(8.dp)
        ) {
            // --- 1. 行番号エリア (Gutter) ---
            // -> TextLayoutResultの情報を元に、Canvasを使って正確なY座標に行番号を描画する
            // 親が無限の縦スクロール領域になるため、Canvasの高さを明示的に計算する
            val textHeight = with(density) {
                (textLayoutResult?.size?.height ?: 0).toDp()
            }
            Canvas(
                modifier = Modifier
                    .width(32.dp)
                    // テキストのレイアウト結果と同じ高さを指定して同期させる
                    .height(textHeight)
            ) {
                println("Text length: ${textFieldValue.text.length}")
                val layoutResult = textLayoutResult ?: return@Canvas
                // 論理行（改行コードで区切られた行）のカウント用
                var logicalLineNumber = 1
                println("Line count: ${layoutResult.lineCount}")
                // 物理行（画面上で実際に折り返されて描画されている行）をループ
                for (i in 0 until layoutResult.lineCount) {
                    // i 番目の物理行がテキスト全体の何文字目 (改行文字含む) から始まるか
                    val lineStartOffset = layoutResult.getLineStart(i)
                    // 注意 (getLineStart の仕様). 0-indexed で考える。
                    // 1. 0 論理行目 = 0 物理行目で、start offset は必ず 0.
                    // 2. テキストの中で、n 行目までが空でなく、n+1 論理行目が k_(n+1) 文字目から始まるとする。
                    //    - もし n+1 論理行目が空なら、文字列は "...\n" の形で、最後の "\n" の位置は k_(n+1) - 1 。このとき、n+1 論理行目の start offset は k_(n+1) - 1 となる。
                    //    - もし n+1 論理行目が空でないなら、n+1 論理行目の start offset は k_(n+1) となる。
                    // 3. n 行目までが空になるというのは、0 行目が空な場合のみ。
                    //    - 文字列が "\n" の場合、2 つの論理行からなる。
                    //    - このとき、最後の 1 論理行目の start offset は 0 となる。
                    // 2. テキストが "\n" なら 2 論理行からなる。
                    //    2 論理行目の start offset は 0 となる。
                    //    テキストが "
                    println("Line startOffset: $lineStartOffset")
                    // その物理行が、論理行の先頭である場合のみ行番号を描画する
                    // （折り返された2行目以降には行番号を書かない）
                    val isFirstLine = (i == 0) // エディタの 1 行目かどうか
                    val isExceptionalCase =
                        (textFieldValue.text.lastOrNull() == '\n') && (textFieldValue.text.getOrNull(lineStartOffset) == '\n') // 例外ケース
                    val isHeadOfLogicalLine =
                        (textFieldValue.text.getOrNull(lineStartOffset - 1) == '\n') // 1 つ前の文字が改行
                    if (isFirstLine || isExceptionalCase || isHeadOfLogicalLine) {

                        // カーソルの現在位置（オフセット）を取得
                        // ※範囲選択されている場合は、便宜上開始位置(start)の行をハイライトします
                        val cursorOffset = textFieldValue.selection.start.coerceIn(0, textFieldValue.text.length)
                        // カーソルがある「物理行（画面上で何行目か）」を取得
                        val currentLineIndex = layoutResult.getLineForOffset(cursorOffset)

                        // drawTextで直接描画する前に、textMeasurerで「行番号のサイズ情報」を計算する
                        val numberLayout = textMeasurer.measure(
                            text = logicalLineNumber.toString(),
                            style = editorTextStyle.copy(
                                color = if (i == currentLineIndex) activeLineColor else Color.Gray
                            )
                        )

                        // その行の「ベースラインのY座標」を取得する
                        val lineBaselineY = layoutResult.getLineBaseline(i)
                        // エディタのベースラインから、行番号自身のベースライン位置を引いて、正しいTop座標を算出する
                        val drawY = lineBaselineY - numberLayout.firstBaseline

                        // 計算したレイアウト情報を使って描画する
                        drawText(
                            textLayoutResult = numberLayout,
                            topLeft = Offset(0f, drawY)
                        )

                        logicalLineNumber++
                    }
                }
            }

            Spacer(modifier = Modifier.width(8.dp))

            // --- 2. テキスト入力エリア ---
            BasicTextField(
                value = textFieldValue, // 入力とカーソル移動のデータ
                onValueChange = {
                    // onEdited(SourceCode(it.text))
                    textFieldValue = it // テキスト更新後にカーソル更新
                },
                textStyle = editorTextStyle,
                onTextLayout = { layoutResult ->
                    // ここでレイアウト情報を取得し、状態を更新する
                    textLayoutResult = layoutResult
                },
                modifier = Modifier
                    .weight(1f) // 画面の右端までの余白をすべて使う
                    //                // 横スクロールはテキストエリアのみにかける
                    //                .horizontalScroll(horizontalScrollState)
                    // drawBehind で BasicTextField の背景に直接描画する
                    .drawBehind {
                        val layoutResult = textLayoutResult ?: return@drawBehind

                        // カーソルの現在位置（オフセット）を取得
                        // ※範囲選択されている場合は、便宜上開始位置(start)の行をハイライトします
                        val cursorOffset = textFieldValue.selection.start.coerceIn(0, textFieldValue.text.length)

                        // カーソルがある「物理行（画面上で何行目か）」を取得
                        val currentLineIndex = layoutResult.getLineForOffset(cursorOffset)

                        // その行の上端(Top)と下端(Bottom)のY座標を取得
                        val lineTop = layoutResult.getLineTop(currentLineIndex)
                        val lineBottom = layoutResult.getLineBottom(currentLineIndex)

                        // エディタの横幅いっぱい（size.width）に、行の高さ分の四角形を描画
                        drawRect(
                            color = activeLineColor,
                            topLeft = Offset(0f, lineTop),
                            size = Size(size.width, lineBottom - lineTop)
                        )
                    }
            )
        }
    }
}

@Preview(
    widthDp = 500,
    heightDp = 300,
    showBackground = true
)
@Composable
fun CodeEditorPreview() {
    CodeEditorUI(
        sourceText = "",
        fontSizeSp = 14f,
        onEdited = {},
    )
}