package com.mono9rome.typst_note_app.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectHorizontalDragGestures
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Menu
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.PointerIcon
import androidx.compose.ui.input.pointer.pointerHoverIcon
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.unit.dp

// リサイザーにホバーしたときのカーソルアイコン
// ※ プラットフォームごとに実装を分ける
expect val horizontalResizeIcon: PointerIcon

// サイドバーの幅の最小・最大値
private val minSidebarWidth = 100.dp
private val maxSidebarWidth = 400.dp

// Remark : The UI logic is generated by Gemini 3 Pro.
@Composable
fun SidebarContainer(
    modifier: Modifier = Modifier,
    content: @Composable (BoxScope.() -> Unit)
) {
    // サイドバーの開閉状態を管理するフラグ
    var isSidebarOpen by remember { mutableStateOf(false) }
    // 実際の表示に使われる、現在のサイドバーの幅
    var sidebarWidth by remember { mutableStateOf(200.dp) }
    // ドラッグ中のマウスカーソルの「本来の位置」を記録する仮想幅
    var virtualSidebarWidth by remember { mutableStateOf(200.dp) }

    // ドラッグ量（ピクセル）を dp に変換するための Density
    val density = LocalDensity.current

    // 全体を横並び(Row)にする
    Row(modifier = modifier.fillMaxSize()) {

        // 1. 一番左の細いメニューバー（常に表示）
        Column(
            modifier = Modifier
                .width(40.dp)
                .fillMaxHeight()
                .background(Color.LightGray), // わかりやすく色をつけています
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // 開閉用のトグルボタン
            IconButton(
                onClick = { isSidebarOpen = !isSidebarOpen },
                modifier = Modifier
                    .size(32.dp)
                    .padding(top = 12.dp)
            ) {
                Icon(
                    imageVector = Icons.Default.Menu,
                    contentDescription = "サイドバー切替",
                    modifier = Modifier.size(18.dp)
                )
            }
        }

        // 2. 開閉するサイドバーの中身
        if (isSidebarOpen) {
            Box(
                modifier = Modifier
                    .width(sidebarWidth) // サイドバーの幅
                    .fillMaxHeight()
                    .background(Color(0xFFEEEEEE)) // メイン画面と区別する色
            ) {
                Text(
                    text = "ファイル一覧など",
                    modifier = Modifier.padding(16.dp)
                )
            }

            // 3. ドラッグ用の境界線（リサイザー）
            Box(
                modifier = Modifier
                    .width(4.dp) // つかみやすいように少し幅を持たせる
                    .fillMaxHeight()
                    .background(Color.DarkGray)
                    .pointerHoverIcon(horizontalResizeIcon)
                    .pointerInput(Unit) {
                        // 水平方向のドラッグを検知
                        detectHorizontalDragGestures(
                            // ドラッグ開始時に、仮想幅を現在の実際の幅にリセットする
                            onDragStart = { virtualSidebarWidth = sidebarWidth },
                            // ドラッグ終了時・キャンセル時にも念のため同期しておく
                            onDragEnd = { virtualSidebarWidth = sidebarWidth },
                            onDragCancel = { virtualSidebarWidth = sidebarWidth }
                        ) { change, dragAmount ->
                            // イベントを消費（他のスクロール要素などに影響を与えないようにする）
                            change.consume()

                            // ピクセル単位の移動量を dp に変換
                            val dragAmountDp = with(density) { dragAmount.toDp() }

                            // 仮想幅にそのまま移動量を足す（マイナスにもなり得る）
                            virtualSidebarWidth += dragAmountDp

                            // 新しい幅を、仮想幅を min と max で切り詰めたものとする（coerceIn）
                            sidebarWidth = virtualSidebarWidth.coerceIn(
                                minimumValue = minSidebarWidth,
                                maximumValue = maxSidebarWidth
                            )
                        }
                    }
            )
        }

        // 4. メインのコンテンツ領域
        Box(
            modifier = Modifier
                .weight(1f) // 残りの幅をすべて埋める
                .fillMaxHeight()
                .background(Color.White)
        ) {
            content()
        }
    }
}